### ISSUE TITLE
Ctrl+S doesn't work on Windows

### ISSUE THREAD

**Issue by bakalogatos** [menpo/landmarker.io#108]
Notes by @jabooth:

Unfortunately on Chrome Windows, Ctrl + S brings up the save webpage dialog, so we can't actually save with the keyboard. Maybe we should just do S? How does something like gmail get around these kind of cross-platform issues?

**Comment by lirsacc** [comment]
We use ctrl to avoid unwanted save as it is reflected on the backend. I feel like just S is too prone to accidental saves.

I think we don't use `preventDefault` on this one though, so it may be a simple fix, but I don't have access to a windows laptop to confirm.

**Comment by jabooth** [comment]
@lirsacc I can try this on Windows tonight.

**Comment by jabooth** [comment]
Confirmed, that works as a fix.

Can you make a PR for the branch and just reference this issue? Now we are incrementally I'd rather have individual PRs to point to for history if possible.

Once that is merged, we can close this issue, and do a patch release.

**Comment by lirsacc** [comment]
Linked to #110 as the refactor encompassed both. Unless it's urgent I'd wait for both to be cleared.

**Comment by jabooth** [comment]
No problem, we'll wait for #110 to get resolved first.

**Comment by jabooth** [comment]
Solved by #122
