### ISSUE TITLE
templates with .yml extension are not recognised in Dropbox

### ISSUE THREAD

**Issue by jabooth** [menpo/landmarker.io#123]
I think both yaml and yml are pretty widespread so should support both:
https://en.wikipedia.org/wiki/YAML

**Comment by lirsacc** [comment]
At which point does this manifest ? I see both extensions and load both test files fine on current live.

![screen shot 2015-10-28 at 17 46 08](https://cloud.githubusercontent.com/assets/1597140/10795966/60767da0-7d9c-11e5-8db1-271cc103cd5e.png)

![screen shot 2015-10-28 at 17 50 17](https://cloud.githubusercontent.com/assets/1597140/10795972/64d78286-7d9c-11e5-99f0-a26c3e23c3d6.png)

**Comment by jabooth** [comment]
I wasn't having it appear in the file picker UI, will confirm once home

**Comment by jabooth** [comment]
My apologies, I can't replicate now. Thinking it must have just been a delay in Dropbox syncing (I did try it twice and so thought it really was a bug, guess I just got unlucky with slow syncs twice).
