### ISSUE TITLE
No gulpfile found

### ISSUE THREAD

**Issue by AAcquier** [menpo/landmarker.io#146]
Hi,
 I am trying to install landmarker but every time I try to run gulp from the project's root directory I get "no gulpfile found" as there is no gulpfile in the  project's root directory.

Is there any one who can tell me what I am doing wrong?

Regards,

Alex Acquier

**Comment by jabooth** [comment]
Apologies, the README was out of date. I just updated it (b1fb1a354a01b9ce90f3f8ba0a08c3d871179fb4) to reflect the right approach (no gulp any more)

**Comment by AAcquier** [comment]
I still get an error when I try to do npm run watch:

![npm screenshot](https://user-images.githubusercontent.com/24592095/43388904-4b316acc-93e2-11e8-9324-9841002c2931.jpg)

I think it is because I am running windows
