### ISSUE TITLE
CTRL+CLICK between groups

### ISSUE THREAD

**Issue by patricksnape** [menpo/landmarker.io#59]
If you CTRL+CLICK you can select landmarks in different groups (visually) however, only the last selected landmark is actually moveable in the canvas. This shouldn't be allowed.

**Comment by lirsacc** [comment]
With snap mode in, using ctrl (or cmd on the sidebar) will start a group selection and allow moving all the selected landmarks around. It allows the kind of selection shown above and keeps behaviour consistent with ctrl clicking on the points.

Solves this bug imo, so if that is valid for you guys I'll go ahead and close this.

**Comment by jabooth** [comment]
Yeah this behavior is now fixed, feel free to close it.
