### ISSUE TITLE
can't mouse over inner element of right hand column

### ISSUE THREAD

**Issue by jabooth** [menpo/landmarker.io#62]

**Comment by jabooth** [comment]
@patricksnape didn't we fix this a few months back?

**Comment by patricksnape** [comment]
I think we worked out a fix, but I'm not sure we ever implemented it.

**Comment by jabooth** [comment]
just checked, we did fix it on master in 2d4d606b08d6f746f8941303b212448dcabd21ba.

Doing a bunch of fixes today, will push out to production this evening.
