### ISSUE TITLE
Safari 8 (Yosemite) doesn't display landmarks sidebar

### ISSUE THREAD

**Issue by jabooth** [menpo/landmarker.io#74]

**Comment by jabooth** [comment]
this feels like something to do with z-indexing, as we also fail to display the help menu when it's brought up...

**Comment by lirsacc** [comment]
Current view on Safari Yosemite:

![screen shot 2015-07-01 at 23 01 44](https://cloud.githubusercontent.com/assets/1597140/8465904/63f64b68-2045-11e5-9f94-5058e398e1ef.png)

I'll close as this seem to no longer be an issue.
