### ISSUE TITLE
Get bug free on all latest browsers (Chrome/FF/Safari/Edge)

### ISSUE THREAD

**Issue by jabooth** [menpo/landmarker.io#75]
Right now the landmarker works without known bugs in Chrome on all platforms. Users should be notified about this if they are in another browser to prevent confusion over bugs.

**Comment by jabooth** [comment]
```js
var isChrome = (typeof window.chrome === "object");
```
seems to be the right way to check
http://stackoverflow.com/questions/6339480/how-to-detect-if-a-browser-is-chrome-using-jquery

**Comment by jabooth** [comment]
Actually Firefox works perfectly now too.

**Comment by jabooth** [comment]
Latest Safari (iOS 8/OS X 10.10) is now also fine. Only #80 and #81 are currently holding us back from IE 11 support. I'd rather now get those problems solved then the landmarker supports all browsers on all platforms - so long as they are up to date.

**Comment by lirsacc** [comment]
For now the version 2 code doesn't work on IE11 (v1 is ok though) and hasn't worked since January, and a nasty flexbox bug (see https://github.com/Modernizr/Modernizr/issues/1301) makes it look strange. 

We drop support for now by displaying a prompt on IE, noone complained since January so it shouldn't affect too many people.

**Comment by jabooth** [comment]
I'm happy to leave IE unsupported frankly, with a prompt suggesting the user installs either Chrome, Firefox, or upgrades to Windows 10 and uses Edge.

I *do* think that after July 29th we should quickly support Edge, which promises to be easy to support as long as we are suporting WebKit:
http://www.neowin.net/news/microsoft-any-edge-to-webkit-differences-are-considered-bugs

**Comment by jabooth** [comment]
Just checked with Edge and we have no obvious issues. Obliviously it will be an ongoing job to ensure we remain bug free on these browsers but closing this issue for now as the milestone is reached.
