### ISSUE TITLE
[backend-restructuring] Changing the landmark template resets to index 1

### ISSUE THREAD

**Issue by jabooth** [menpo/landmarker.io#99]
Reproduce - move to any asset in a collection. Upon changing the template, you are taken back to the start of the collection

Expected behaviour - user is kept on this asset, just the landmarks used are changed.

**Comment by lirsacc** [comment]
Currently not seeing the described behaviour on staging or local, may have been transient and fixed in between commits.
Can you confirm @jabooth ?
